# Generated by Django 6.1.1 on 2026-10-01 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del recurso')),
                ('resource_type', models.CharField(choices=[('SPORT', 'Pista Deportiva'), ('ROOM', 'Sala de Reuniones'), ('EQUIP', 'Equipamiento')], default='SPORT', max_length=10, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('end_time', models.DateTimeField(verbose_name='Fecha y hora de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='¿Es recurrente?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reservas.resource', verbose_name='Recurso')),
            ],
        ),
    ]
